### ISSUE TITLE
Job fails with nested directories in workspace

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/js#186]
https://app.dependencies.io/j/ea42c64a-76d8-4c9c-ace7-1d59fbfdada6

We have following entries in workspaces:
```
"addons/*",
"addons/storyshots/*"
```

there's no `addons/storyshots/package.json`, the directory contains two nested packages instead: https://github.com/Hypnosphi/storybook/tree/master/addons/storyshots

Both yarn and lerna work OK with this structure.

**Comment by Hypnosphi** [comment]
You can use [`yarn workspaces info --json`](https://yarnpkg.com/en/docs/cli/workspaces#toc-yarn-workspaces-info) command to list all the actually present workspaces

**Comment by davegaeddert** [comment]
Good call. I think I looked for something like that originally.
