### ISSUE TITLE
Show only direct dependencies in Lockfile update PR message

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/js#190]
Otherwise it doesn't fit: https://github.com/Hypnosphi/storybook/pull/1, note the cutoff on "`babel-plugi"

**Comment by davegaeddert** [comment]
It is only showing the direct dependencies there.

**Comment by Hypnosphi** [comment]
Oh I see. OK that's probably because we haven't updated for a while. Can it then split into multiple messages when there are too many characters?

**Comment by davegaeddert** [comment]
Moved this here: https://github.com/dependencies-io/deps/issues/22
