### ISSUE TITLE
Option to include in-range package.json updates?

### ISSUE THREAD

**Issue by davegaeddert** [dependencies-io/js#7]
See this conversation: https://github.com/dependencies-io/actor-js-lerna/issues/39#issuecomment-369032906

Basically, there's a chance we may want an option here to not remove versions satisfied by the current constraint, so that they flow through and can be provided in a manifest update (even though they are in-range of the original constraint).

**Comment by davegaeddert** [comment]
2 ideas here. 

1. Make a separate package that does this. Its job is to update the minimum end of ranges in package.json. After a `yarn upgrade` you could look at the installed versions of the ranges, then update the package.json range to be at least that version. https://github.com/dependencies-io/actor-js-lerna/issues/39#issuecomment-373205150

2. If we do a commit for each direct dependency (granular lockfile update) then maybe it makes sense just to build it in here as an option depending on how that is actually built.

**Comment by Hypnosphi** [comment]
> If we do a commit for each direct dependency

That's a very valuable feature of v1
